[tool.poetry]
name = "Scint Workers"
version = "0.1.0"
description = "Structured, composable intelligence"
authors = ["Tim Kaechle <timothy.kaechle@me.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "scint"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
openai = "^1.2.1"
asyncio = "^3.4.3"
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"
loguru = "^0.7.2"
xdg-base-dirs = "^6.0.1"
python-dotenv = "^1.0.0"
tiktoken = "^0.5.1"
numpy = "^1.26.1"
aiohttp = "^3.9.1"
discord = "^2.3.2"
apscheduler = "^3.10.4"
tenacity = "^8.2.3"
scint = {path = "../scint/dist/scint-0.3.6.tar.gz"}
aiofiles = "^23.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
